### ISSUE TITLE
Story: Improve documentation of detekt

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#496]
This is the story ticket to sum up all documentation improvements which need to be done for a GA release:

- [x] Kdoc for all rules
    - [x] complexity rule set
    - [x] style rule set
    - [x] potential bugs rule set
    - [x] comments rule set
    - [x] performance rule set
    - [x] exceptions rule set
    - [x] empty-blocks rule set
- [x] generate default config based on Kdoc and sources #189
- [x] github pages website with rule browsing, generate markdown page for each rule based on Kdoc
- [x] example extension project should have `build.gradle` and `pom.xml` #438
- [X] ~~split readme into wiki pages #192, #17~~
- [x] populate site with useful infos and how-tos from readme
- [x] finalize rule names #109

**Comment by Mauin** [comment]
Some KDoc for the `performance` ruleset was done in #563

**Comment by arturbosch** [comment]
Every point on the list was done. If something is unclear or not documented out users will tell us ^^.
